"""Archive of curated opening lines (the June 2026 ~236-line expansion).

This file is NOT imported or run. It is a curation resource: when editing the
active GARBAGE_LINES in send_reminder.py, draw replacement lines from here.
Apply the curation rules in MAINTENANCE.md (facts/cozy over jokes; named
characters with a real bin tie; GSM-7 safe; one-segment length). Preserved here
because the repo history was squashed for the public release.
"""

ARCHIVE_LINES = [
    # --- general (fits any bin) ---
    ("general", "Lille fakta: hver dansker smider omkring 750 kg affald ud om året."),
    ("general", "Dagrenovationen i Danmark er faldet 37% siden 2011, fordi vi sorterer mere."),
    ("general", "Der er noget rart ved en tom beholder en tidlig morgen."),
    ("general", "Skraldemanden er en af de få, der altid kommer, som han lover."),
    ("general", "Tak til skraldemændene, der står tidligt op, så vi andre slipper."),
    ("general", "Der er en stille tilfredshed i at få ryddet op før weekenden."),
    ("general", "Der er noget gammeldags hyggeligt ved at følge skraldekalenderen sammen."),
    ("general", "En tom skraldespand er en lille frisk start på dagen."),
    ("general", "At sortere rigtigt er en af de nemmeste gode vaner, vi har."),
    ("general", "Lidt oprydning gør hele huset lettere at være i."),
    ("general", "En fast rutine gør selv skraldedagen til noget trygt."),
    ("general", "Det er rart at vide præcis, hvad der skal ud og hvornår."),
    ("general", "Genbrug betyder bare, at tingene får et liv mere."),
    ("general", "En ryddet indgang møder en med ro om morgenen."),
    ("general", "Små vaner som sortering tæller op over et helt år."),
    ("general", "Der er noget godt ved at gøre ugen klar sammen."),
    ("general", "Det føles godt at sende noget videre i kredsløbet."),
    ("general", "En ren beholder lugter bedre hele ugen."),
    ("general", "At gøre plads er en lille gave til sig selv."),
    ("general", "Lidt orden i tingene gør hele ugen lettere."),
    ("general", "Jo bedre vi sorterer, jo mindre skal brændes."),
    ("general", "Sortering derhjemme er det første led i genbrugskæden."),
    ("general", "Rent og tørt affald er nemmere at genbruge end vådt og blandet."),
    ("general", "Mange materialer kan genbruges igen og igen."),
    ("general", "Det meste husholdningsaffald i Danmark bliver genbrugt i dag."),
    ("general", "Det vi sorterer fra, slipper for at ende i ovnen."),
    ("general", "Genbrug sparer både råstoffer og energi."),
    ("general", "En stille morgenrutine gør resten af dagen lettere."),
    ("general", "At have styr på ugens skraldedage er en lille luksus."),
    ("general", "Det er rart, når hjemmet og kalenderen følges ad."),
    ("general", "En god uge starter tit med en tømt beholder."),
    ("general", "Vinteren kommer, men skraldekalenderen holder året rundt."),
    # --- haveaffald ---
    ("haveaffald", "Vidste du det? Vi sorterer i snit 118 kg haveaffald pr. person om året."),
    ("haveaffald", "Om foråret kan man ofte hente gratis kompost på genbrugspladsen."),
    ("haveaffald", "Grønt tip: en gren klippet i stykker på 20-30 cm komposterer hurtigere."),
    ("haveaffald", "Det tager typisk 1-2 år for en bunke haveaffald at blive til muld."),
    ("haveaffald", "Det meste haveaffald i Danmark ender som kompost i haverne."),
    ("haveaffald", "Når bladene falder, samler haveaffaldet sig helt af sig selv."),
    ("haveaffald", "Forår i haven betyder grene, blade og den gode følelse af at rydde op."),
    ("haveaffald", "En ryddet have om foråret er en af de billigste glæder, der findes."),
    ("haveaffald", "Haveaffald bliver til kompost og kommer tilbage som muld."),
    ("haveaffald", "Blade, græs og grene hører til i haveaffaldet."),
    ("haveaffald", "En kompostbunke skal bruge både grønt og brunt for at trives."),
    ("haveaffald", "Vend kompostbunken en gang imellem, så går det hurtigere."),
    ("haveaffald", "Tørre blade og grene er det brune, kompostbunken har brug for."),
    ("haveaffald", "Græsafklip kan lægges som tæppe under buske."),
    ("haveaffald", "Små grene komposterer hurtigere end store."),
    ("haveaffald", "Haveaffald uden plast og potter bliver den bedste kompost."),
    ("haveaffald", "En kompost i gang lugter af skovbund, ikke af affald."),
    ("haveaffald", "Efterårets blade i dag er havens muld næste år."),
    ("haveaffald", "Selv ukrudt kan komposteres, hvis det ikke har sat frø."),
    ("haveaffald", "Det grønne, vi luger væk, bliver til næring igen."),
    ("haveaffald", "Lad lidt blade ligge - de er ly for haven om vinteren."),
    ("haveaffald", "Beskårne grene fylder mindre, hvis de klippes i små stykker."),
    ("haveaffald", "Haveaffald er havens eget kredsløb, der starter forfra."),
    ("haveaffald", "Kompost er gratis gødning, haven selv laver."),
    ("haveaffald", "Der er noget fredeligt ved at samle blade en stille efterårsdag."),
    ("haveaffald", "Foråret melder sig, så snart de første grene skal beskæres."),
    ("haveaffald", "En have, der passes, giver lidt tilbage hver sæson."),
    ("haveaffald", "Lugten af nyslået græs er sommerens første tegn."),
    ("haveaffald", "At rydde i bedene om foråret er som at trække vejret dybt."),
    ("haveaffald", "Haveaffald må gerne fylde - det bliver alligevel til muld."),
    ("haveaffald", "Stauder, der klippes ned om efteråret, kommer stærkt igen."),
    ("haveaffald", "En kompost giver haven gratis næring år efter år."),
    ("haveaffald", "Hækkeklip fylder meget, men komposterer fint i små stykker."),
    ("haveaffald", "Det grønne affald i dag er næste års blomster."),
    ("haveaffald", "En velpasset kompost er havens lille kraftværk."),
    ("haveaffald", "Blade i bunke bliver til den fineste bladmuld."),
    ("haveaffald", "Haven samler altid lidt sammen, der skal videre."),
    ("haveaffald", "Frisk beskæring giver lys og luft til resten af haven."),
    ("haveaffald", "Visne potteplanter kan også gå til haveaffald."),
    ("haveaffald", "Nedfaldsfrugt fra træerne hører til i haveaffaldet."),
    ("haveaffald", "Et bed, der luges rent, ser straks større ud."),
    ("haveaffald", "Mos og blade fra græsplænen kan komposteres."),
    ("haveaffald", "Lidt haveaffald hver uge er nemmere end en kæmpebunke."),
    ("haveaffald", "Når man river blade sammen, dukker efteråret rigtigt op."),
    ("haveaffald", "En kompost i hjørnet er havens stille genbrugsstation."),
    ("haveaffald", "Det grønne fra haven er en ressource, ikke rigtig affald."),
    ("haveaffald", "Grene og kvas fylder, men bliver til fin flis og muld."),
    ("haveaffald", "Det meste fra havesæsonen kan blive til ny vækst."),
    ("haveaffald", "Sam Gamgee var gartner - han ville elske vores haveaffald."),
    ("haveaffald", "Groot er selv et træ - han ville føle sig hjemme i haveaffaldet."),
    ("haveaffald", "Carmy ved, at de bedste krydderurter starter i havens jord."),
    ("haveaffald", "Neville Longbottom var bedst til urtologi - han ville elske havearbejdet."),
    # --- pap (genuine advice only) ---
    ("pap", "Lille detalje: pap og papir fylder omkring 34 kg pr. dansker om året."),
    ("pap", "Pap kan genbruges mange gange og bliver til nyt pap og karton."),
    ("pap", "Genbrugt pap sparer både træer, vand og energi."),
    ("pap", "Fladt pap fylder mindre og er nemmere at genbruge."),
    ("pap", "Slå kassen sammen, så er der plads til mere i beholderen."),
    ("pap", "Tag tape og flamingo af pappet - kun rent pap skal i."),
    ("pap", "Vådt eller fedtet pap hører ikke til genbrugspappet."),
    ("pap", "En pizzabakke med fedtpletter er desværre ikke rent pap."),
    ("pap", "Rent og tørt pap bliver nemt til nyt pap igen."),
    ("pap", "Pap er en af de nemmeste ting at genbruge rigtigt."),
    ("pap", "En flad papkasse fylder næsten ingenting."),
    ("pap", "Pap bliver til nye kasser, æggebakker og karton."),
    ("pap", "Jo renere pappet er, jo bedre bliver det nye pap."),
    ("pap", "Lidt sammenfoldet pap gør stor forskel i beholderen."),
    ("pap", "Skil pap og plast ad, så genbruges begge bedst."),
    ("pap", "En tom flyttekasse er ren pap og kan genbruges."),
    ("pap", "Karton fra køkkenet kan gå i pappet, hvis det er rent."),
    ("pap", "Det meste pap kan blive til pap igen mange gange."),
    ("pap", "Papkasser er lavet til at blive genbrugt."),
    ("pap", "Tørt pap er guld i genbruget."),
    ("pap", "Riv tape af, så er pappet klar til genbrug."),
    ("pap", "En papkasse fladet ud er en mindre tur til pladsen."),
    ("pap", "Pap er let, rent og nemt at sende videre."),
    ("pap", "Genbrugt pap bliver til alt fra kasser til byggeplader."),
    ("pap", "Selv små papæsker tæller med i genbruget."),
    ("pap", "Pap fylder hurtigt, men fladet ud fylder det næsten intet."),
    ("pap", "Tørt og rent pap er den nemmeste sortering, der findes."),
    ("pap", "Saml pappet fladt, så fylder en uges kasser ingenting."),
    ("pap", "Bølgepap bliver til nyt bølgepap igen og igen."),
    ("pap", "En ren papkasse er klar til et helt nyt liv."),
    ("pap", "Fold de store kasser, så er der plads til de små."),
    ("pap", "Pap uden mad og fedt giver det bedste genbrug."),
    ("pap", "Køkkenrullens og toiletrullens rør er også pap."),
    ("pap", "Skotøjsæsker og flyttekasser hører begge til pap."),
    ("pap", "En velfoldet papkasse er en lille sejr på en papdag."),
    ("pap", "Mælkekartoner er ikke pap - de hører til kartoner."),
    ("pap", "Papfibre kan genbruges mange gange, før de bliver for korte."),
    ("pap", "Æggebakker af pap er allerede genbrugt mindst en gang."),
    ("pap", "Pap fra pakker fylder mest - og genbruges bedst fladt."),
    ("pap", "Der er noget tilfredsstillende ved at folde en stor kasse helt flad."),
    ("pap", "En ryddelig stak fladt pap er næsten pænt at se på."),
    ("pap", "Det er rart at sende ugens pakker videre som rent pap."),
    ("pap", "En tom papkasse bliver tit en leg for et barn først."),
    ("pap", "At brække kasserne ned er ugens nemmeste oprydning."),
    ("pap", "Pap vejer næsten ingenting - det er let at bære ud."),
    ("pap", "Der er ro i at se beholderen tage imod en uges kasser."),
    ("pap", "Fjern plasten fra papkasser, så pappet bliver rent."),
    ("pap", "Tørt pap genbruges bedst - vådt pap taber styrke."),
    ("pap", "En foldet papkasse fylder kun en brøkdel af en åben."),
    ("pap", "Online-handel giver pap - heldigvis kan det hele genbruges."),
    # --- storskrald ---
    ("storskrald", "En gammel stol til storskrald bliver måske til nogen andens fund."),
    ("storskrald", "Storskrald er tit de ting, der har tjent os længe og nu skal videre."),
    ("storskrald", "Meget storskrald kan skilles ad og genbruges - møbler, metal og træ."),
    ("storskrald", "Møbler, der stadig duer, kan doneres i stedet for at smides ud."),
    ("storskrald", "Skil møbler ad, så genbruges træ og metal hver for sig."),
    ("storskrald", "Meget storskrald får et nyt liv, hvis det stilles pænt frem."),
    ("storskrald", "Et gammelt møbel kan blive til en andens skattefund."),
    ("storskrald", "Storskrald er en god anledning til at give plads i hjemmet."),
    ("storskrald", "Det, der har tjent os længe, kan stadig blive til nytte."),
    ("storskrald", "Metal fra storskrald kan smeltes om og bruges igen."),
    ("storskrald", "Træmøbler kan blive til spånplader eller energi."),
    ("storskrald", "En oprydning i kælderen føles næsten som en lille sejr."),
    ("storskrald", "Det er rart at give slip på det, vi ikke længere bruger."),
    ("storskrald", "Storskrald er ofte det, vi har gemt lige et stykke tid endnu."),
    ("storskrald", "En tømt kælder giver luft til nye ting."),
    ("storskrald", "At rydde ud er at gøre plads til det, der betyder noget."),
    ("storskrald", "Gamle apparater hører til storskrald, ikke i restaffaldet."),
    ("storskrald", "Et slidt møbel kan ofte repareres i stedet for at skiftes."),
    ("storskrald", "Storskrald hentes samlet, så meget kan komme afsted på en gang."),
    ("storskrald", "Stil storskraldet pænt frem, så andre nemt kan se det."),
    ("storskrald", "Sorter storskraldet groft, så genbruget bliver lettere."),
    ("storskrald", "Et gammelt skab kan blive til en andens første møbel."),
    ("storskrald", "Det føles let at give slip, når det kommer videre til nytte."),
    ("storskrald", "Mange genbrugspladser tager gerne imod brugbare møbler."),
    ("storskrald", "Storskrald er det store ryk, der gør plads til ro."),
    ("storskrald", "En udtjent seng kan skilles ad og genbruges i dele."),
    ("storskrald", "Gamle ting, der gives videre, holder ofte længere endnu."),
    ("storskrald", "At rydde ud i det store er en lettelse, man kan mærke."),
    ("storskrald", "En tom plads, hvor det gamle stod, er en stille glæde."),
    ("storskrald", "Det meste storskrald kan genbruges, hvis det sorteres."),
    ("storskrald", "Giv møblet en sidste tur ud - nogen kan måske bruge det."),
    ("storskrald", "En god udmugning rydder både i hjemmet og i hovedet."),
    ("storskrald", "Et stykke gammelt træ kan få nyt liv i andres hænder."),
    ("storskrald", "Storskraldsdagen er en god anledning til at rydde garagen."),
    ("storskrald", "En gammel reol kan blive til hylder et helt andet sted."),
    ("storskrald", "Det tunge, der skal ud, bliver lettere, når det hentes samlet."),
    ("storskrald", "En udslidt sofa kan skilles ad - skum, træ og metal hver for sig."),
    ("storskrald", "Når noget stort er kørt væk, virker hele rummet større."),
    ("storskrald", "Defekt elektronik som tv og højttalere hører til storskrald."),
    ("storskrald", "Et møbel, der gives videre, fortæller sin historie igen."),
    ("storskrald", "Storskrald, der stilles pænt, finder hurtigere en ny ejer."),
    ("storskrald", "Det gamle ud, det nye ind - storskrald gør plads."),
    ("storskrald", "En oprydning i skuret er tit en hel storskraldsdag værd."),
    ("storskrald", "Brugbare møbler kan ofte hentes af genbrugsbutikker."),
    ("storskrald", "At skille tingene ad gør genbruget af storskrald nemmere."),
    ("storskrald", "En tom carport efter storskrald er en lille triumf."),
    ("storskrald", "Gamle cykler og redskaber kan også være storskrald."),
    ("storskrald", "Jerntronen er nok historiens mest upraktiske møbel til storskrald."),
    ("storskrald", "Carrie elskede en oprydning i skabet - storskrald er samme følelse."),
    ("storskrald", "Ross' berygtede sofa fra Friends ville være endt som storskrald."),
    ("storskrald", "Tony Stark skrottede gamle dragter for at gøre plads - ren storskrald."),
    ("storskrald", "Ted Mosby gemte på alt - en storskraldsdag ville gøre ham godt."),
    # --- farligt affald ---
    ("farligt", "Batterier, maling, kemikalier og elektronik er farligt affald."),
    ("farligt", "Sparepærer indeholder en smule kviksølv og hører til farligt affald."),
    ("farligt", "Farligt affald lyder voldsomt - men det er bare maling, batterier og pærer."),
    ("farligt", "Batterier hører aldrig i skraldespanden - de skal afleveres for sig."),
    ("farligt", "Maling, lim og kemikalier skal afleveres som farligt affald."),
    ("farligt", "Gamle batterier kan lække, hvis de blandes med andet affald."),
    ("farligt", "Elektronik indeholder stoffer, der skal håndteres for sig."),
    ("farligt", "Spraydåser hører til farligt affald, også når de er tomme."),
    ("farligt", "En gammel mobil er både elektronik og farligt affald."),
    ("farligt", "Medicinrester afleveres på apoteket, ikke i skraldet."),
    ("farligt", "Lavenergipærer og lysstofrør skal afleveres som farligt affald."),
    ("farligt", "Aflever batterier samlet - en pose kan stå klar derhjemme."),
    ("farligt", "Genbrugspladsen tager imod farligt affald gratis."),
    ("farligt", "Akkumulatorer og bilbatterier er farligt affald."),
    ("farligt", "Kemi i afløbet skader mere end vi tror - aflever det i stedet."),
    ("farligt", "Tomme malingsbøtter med rester hører til farligt affald."),
    ("farligt", "Olie og terpentin må aldrig hældes i kloakken."),
    ("farligt", "Sorter farligt affald, så det ikke skader resten af genbruget."),
    ("farligt", "Selv små batterier indeholder metaller, der skal genvindes."),
    ("farligt", "Knapcellebatterier er små, men hører til farligt affald."),
    ("farligt", "Farligt affald sorteret rigtigt holder miljøet rent."),
    ("farligt", "Spildolie kan genraffineres, hvis den afleveres rigtigt."),
    ("farligt", "Elektronik kan genbruges for både metal og sjældne stoffer."),
    ("farligt", "Rester af rengøringsmidler er også farligt affald."),
    ("farligt", "Lad farligt affald blive i sin egen pose, indtil det afleveres."),
    ("farligt", "Maling tørrer ind, men resterne er stadig farligt affald."),
    ("farligt", "Termometre med kviksølv er farligt affald."),
    ("farligt", "Neglelak og fjerner hører faktisk til farligt affald."),
    ("farligt", "Aflever elektronik samlet - selv ledninger kan genbruges."),
    ("farligt", "Et fladt batteri er stadig farligt affald."),
    ("farligt", "Hold kemikalier i original emballage, så ved man hvad det er."),
    ("farligt", "Pesticider og gift fra skuret er farligt affald."),
    ("farligt", "Lightere og lightergas hører til farligt affald."),
    ("farligt", "Farligt affald skal aldrig brændes hjemme."),
    ("farligt", "Det meste elektronik kan genbruges, hvis det afleveres rigtigt."),
    ("farligt", "Saml årets batterier ét sted og aflever dem på en gang."),
    ("farligt", "Genopladelige batterier er også farligt affald, når de er udtjente."),
    ("farligt", "En gammel skærm indeholder stoffer, der skal håndteres for sig."),
    ("farligt", "Trykflasker og gasdåser hører til farligt affald."),
    ("farligt", "Kasseret elværktøj er både elektronik og farligt affald."),
    ("farligt", "Smid aldrig batterier i restaffaldet - de hører til for sig."),
    ("farligt", "Elsparepærer og LED hører til elektronik og farligt affald."),
    ("farligt", "Det farlige affald fylder lidt, men betyder meget at sortere rigtigt."),
    ("farligt", "Hobbymaling og lak hører også til farligt affald."),
    ("farligt", "Når batteriet er dødt, er det stadig ikke skraldespandsaffald."),
    ("farligt", "Saml kemi og maling sammen til en samlet tur på pladsen."),
    ("farligt", "Med stor kraft følger stort ansvar - også for gamle batterier."),
    ("farligt", "Wildfire i Game of Thrones var ren kemi - hold den slags væk fra ild."),
    ("farligt", "Snapes eliksirer skulle behandles varsomt - lige som vores kemi."),
    ("farligt", "Tony Starks reaktor var ren energi - vores batterier afleveres bare for sig."),
]

